### ISSUE TITLE
Please use Rubenwardy's official modding book

### ISSUE THREAD

**Issue by Montandalar** [ivo-bloechliger/luanti_rectangle_builder#1]
Hi Ivo,

After noticing your mod go up on the forums and browsing the code, I couldn't help but notice you left in a comment that refers to the Metadata chapter of the modding book. However, you should be aware that your reference is an old and outdated mirror by competitor project "Final Minetest" (note the .org domain instead of .net - different ownership). Rubenwardy is the author of the modding book and has continued to update it, whereas the Final Minetest mirror has not been updated. Unfortunately, a lot of people accidentally stumble on the dot org book in search results.

I know this doesn't affect the actual code, but your reference should be [ruben's copy](https://rubenwardy.com/minetest_modding_book/en/map/storage.html) instead. Hopefully you find it more useful.

Regards

**Comment by ivo-bloechliger** [comment]
Many thanks! I made the changes.
